#+TITLE: Note

* split multi aspek
hanya bisa handle kasus ideal
belum bisa handle kalimat yang satu aspek tapi ada kata konjungsi
regex masih perlu diperbaiki https://regex101.com/r/iV5qU1/2
** case kalimat yang perlu dipecah (ideal)
- Ruangan sudah sejuk, hanya beberapa ruang saja yang belum memadai -> 1 | 1
- Dosen-dosen yang mengajar sudah sangat baik dalam hal mengajar hanya saja terkadang dosen memberi nilai kurang besar -> 1 | 1
- Sudah cukup baik, tetapi ada beberapa pengajar yang tidak memberikan contoh secara nyata sehingga membuat mahasiswa kurang mengerti materi yang disampaikan -> 0 | 1
- Beberapa pengajar sudah mengajar dengan baik, namun ada juga yang belum baik.
  -> 1 | 0
- sarana prasarana sudah baik, namun ada beberapa ruang kelas yang masih perlu diperbaiki 1 | 1
- menjelaskan dengan baik, hanya saja terkadang terlalu cepat dalam penyampaian materi sehingga sulit dipahami
** kasus kalimat satu aspek tapi ada kata konjungsi
- Kondisi perkuliahan kurang kondusif dengan jumlah mahasiswa lebih dari 50 orang dalam 1 ruang kelas, dengan hanya 1 tenaga pengajar selama lebih dari 3 sks
- mahasiswa akan lebih tertarik dengan adanya latihan-latihan soal dibandingkan hanya terus diterangkan tentang materi yang diajarkan.
- menurut saya pengajar kuliah informatika yang sekarang ini hanya beberapa saja yang memang benar-benar menguasai bidang yang diajarkan.
- kurang transparan untuk nilai akhir semester, di siakad dna juga hanya berisi indeks saja bukan rincian-rincian nilainya dari awal semester hingga akhir
** solusi split kalimat
*** deteksi kata konjungsi terus lalu keputusan pimsaihnya adalah apakah dikedua sisia ada nounphrase.
* Normalisasi teks
** transform kata tidak baku
** handle singkatan kata
** kesalahan ketik
** bahasa asing
* trasnform fitur
frekuensi, frekuensi_stemming, tfidf, tfidf_stemming, postagger, word2_vec_mean, word2_vec_idf
** fitur set
    | no | frekuensi | frekuensi_stemming | tfidf | tfidf_stemming | postagger | word2_vec_mean | word2_vec_idf |
    |----+-----------+--------------------+-------+----------------+-----------+----------------+---------------|
    |  1 | yes       | no                 | no    | no             | yes       | yes            | no            |
    |  2 | yes       | no                 | no    | no             | yes       | no             | yes           |
    |  3 | no        | yes                | no    | no             | yes       | yes            | no            |
    |  4 | no        | yes                | no    | no             | yes       | no             | yes           |
    |    |           |                    |       |                |           |                |               |
    |  5 | no        | no                 | yes   | no             | yes       | yes            | no            |
    |  6 | no        | no                 | yes   | no             | yes       | no             | yes           |
    |  7 | no        | no                 | no    | yes            | yes       | yes            | no            |
    |  8 | no        | no                 | no    | yes            | yes       | no             | yes           |
* contoh kalimat yang harus di split 1
1) 'Ruangan NN sudah MD sejuk NN , , hanya RB beberapa CDI ruang NN saja RB yang SC belum NEG memadai VBI ',
2) 'Dosen NNP - - dosen NN yang SC mengajar VBT sudah MD sangat RB baik JJ dalam IN hal NN mengajar VBT hanya RB saja RB terkadang RB dosen NN memberi VBT nilai NN kurang RB besar JJ ',
3) 'Sudah RB cukup JJ baik JJ , , tetapi CC ada VBI beberapa CDI pengajar NN yang SC tidak NEG memberikan VBT contoh NN secara IN nyata JJ sehingga SC membuat VBT mahasiswa NN kurang RB mengerti VBT materi NN yang SC disampaikan VBT ',
4) 'Beberapa CDI pengajar NN sudah MD mengajar VBT dengan IN baik JJ , , namun CC ada VBI juga RB yang SC belum NEG baik JJ ',
5) 'sarana NN prasarana NN sudah MD baik JJ , , namun CC ada VBI beberapa CDI ruang NN kelas NN yang SC masih RB perlu RB diperbaiki VBT ',
6) 'menjelaskan VBI dengan IN baik JJ , , hanya RB saja RB terkadang RB terlalu RB cepat JJ dalam IN penyampaian NN materi NN sehingga SC sulit JJ dipahami VBT '
* contoh kalimat yang harus di split 2
1) 'Kondisi NN perkuliahan NN kurang RB kondusif JJ dengan IN jumlah NN mahasiswa NN lebih RB dari IN 50 CDP orang NN dalam IN 1 CDP ruang NN kelas NN , , dengan IN hanya RB 1 CDP tenaga NN pengajar NN selama IN lebih RB dari IN 3 CDP sks NN ',
2) 'mahasiswa NN akan MD lebih RB tertarik VBI dengan IN adanya NNG latihan NN - - latihan NN soal NN dibandingkan VBT hanya RB terus RB diterangkan VBT tentang IN materi NN yang SC diajarkan VBT . . ',
3) 'menurut VBT saya PRP pengajar NN kuliah NN informatika NN yang SC sekarang NN ini DT hanya RB beberapa CDI saja RB yang SC memang RB benar JJ - - benar JJ menguasai VBT bidang NN yang SC diajarkan VBT . . ',
4) 'kurang RB transparan JJ untuk IN nilai NN akhir JJ semester NN , , di IN siakad NN dna NN juga RB hanya RB berisi VBT indeks NN saja RB bukan NEG rincian NN - - rincian NN nilainya NN dari IN awal JJ semester NN hingga CC akhir JJ '
* note
a) jangan lupa update key text
b) kata konjungsi jangan dibuang
c) besok benerin algorithm untuk split kalimat
* note 2
- kalo dalam satu kalimat ada lebih dari satu kata konjungsi splitnya dimana?
- benerin juga untuk multi aspek yang lebih dari satu aspek gimana?
- conjungsi diawal kalimat gimana?
